services:
  file-upload-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-upload-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src/uploads:/app/src/uploads
    restart: unless-stopped
